version: '3'
services:
  backend:
    build: ./backend
    user: root
    ports:
      - 8080
    volumes:
      - /opt/db:/opt/db
    env_file:
      - .env
    restart: always
  frontend:
    build: ./frontend
    ports:
      - 5000
    restart: always
    links:
      - backend
  nginx:
    build: ./nginx
    ports:
    - 80:80
    links:
      - frontend
